### ISSUE TITLE
Map fetching fails in edge cases

### ISSUE THREAD

**Issue by LW2904** [LW2904/maniac#13]
The current approach to finding beatmap folders relies on the belief that the respective difficulty strings are always at least 60% smaller than the name strings. This is not always true.

A refactoring of the folder searching algorithm is necessary.

**Comment by ssCherry** [comment]
What it? 
![cmd](https://user-images.githubusercontent.com/42537021/44407133-02fa3780-a566-11e8-80f2-233ddbc7c3c8.png)

**Comment by ssCherry** [comment]
there is such a problem. 
![terminal2](https://user-images.githubusercontent.com/42537021/44408178-83ba3300-a568-11e8-8ec8-5fb6a91b08b1.png)
I will then delete it

**Comment by LW2904** [comment]
@ssCherry Please [create an Issue](https://github.com/LW2904/maniac/issues/new) and add all relevant details. I will delete our conversation here once you have done that.

**Comment by LW2904** [comment]
This was largely mitigated in the `find_beatmap` refactor.
