### ISSUE TITLE
I am not sure what to do

### ISSUE THREAD

**Issue by ueasbfujsabfna2331** [LW2904/maniac#18]
![idk](https://user-images.githubusercontent.com/43121279/45269760-20753f80-b448-11e8-81b2-af4c69a5ee1a.png)

Help me, please. I have no idea what to do!

**Comment by LW2904** [comment]
Since I'm already here... I just added [binaries for 0.2.1](https://github.com/LW2904/maniac/releases/tag/0.2.1), just in case compilation keeps failing.

**Comment by LW2904** [comment]
Closing since the issue is fixed as far as I can tell.
