### ISSUE TITLE
code execution cannot proceed

### ISSUE THREAD

**Issue by recreationx** [LW2904/maniac#20]
The code execution cannot proceed because libwinpthread-1.dl was not found. Reinstalling the program may fix this problem.

Some help please? I installed basic MinGW

**Comment by RazorApple** [comment]
same issue please help @LW2904

**Comment by LW2904** [comment]
Are you getting this error when attempting to compile or when running one of the provided binaries?

**Comment by LW2904** [comment]
With [0.2.2](https://github.com/LW2904/maniac/releases/tag/v0.2.2) I've added a statically linked build, it should fix the error you are getting.

This is of course only a temporary measure until I get to the crux of the issue.

**Comment by LW2904** [comment]
`maniac` does not depend on any version of NodeJS. Could you give me a description of how you start the cheat and the game? The error you are getting indicates `find_beatmap` or `get_window_title` failure; both of which work fine on my testing VMs.

I've added a static debug build which will produce additional logging output which should help to shed some light on this.

**Comment by RazorApple** [comment]
Static - Works
Static Debug - Works
Non Static - DOES NOT WORK (Same issue as before)

**Comment by RazorApple** [comment]
It pares everything but the only thing that throws an error is the non staic build @LW2904

**Comment by LW2904** [comment]
That's good to hear -- I think I'll make the statically linked version the default for releases.

Are you on a x32 system by any chance?

**Comment by LW2904** [comment]
Are you getting the `libwinpthread-1.dll` error on your x64 machine as well? In some cases, it seems to be an issue limited to the x32 platform.

**Comment by LW2904** [comment]
Closing this since it was resolved starting with v0.3.10.
