### ISSUE TITLE
Not parse hitpoints

### ISSUE THREAD

**Issue by xxCherry** [LW2904/maniac#21]
![default](https://user-images.githubusercontent.com/42537021/45931148-1e47d080-bf72-11e8-90ba-f395f65fe447.png)

**Comment by LW2904** [comment]
Can you confirm that this is happening with version 0.2.2? I fixed an issue that would cause parsing failure on Windows.

**Comment by ssCherry** [comment]
yes

**Comment by LW2904** [comment]
This is almost certainly related to #33, see [this comment](https://github.com/LW2904/maniac/issues/33#issuecomment-619114286). Closing since this issue has gone stale.
