### ISSUE TITLE
Sticky keys

### ISSUE THREAD

**Issue by Deathreus** [LW2904/maniac#22]
The 6th token in a beatmap that tells it when a slider ends isn't guaranteed to be 0, this causes end times in the actions that are too small and the key it pressed will be stuck in the 'pressed' state until another note passes it

In `static int parse_hitobject_line(char *line, int columns, struct hitpoint *point)` I suggest the following
```diff
	char *ln = strdup(line), *token = NULL;
+	bool slider = false;
...
		switch (i++) {
		// X
		case 0: point->column = secval / (COLS_WIDTH / columns);
			break;
		// Start time
		case 2: point->start_time = secval;
			break;
+		case 3: slider = (secval == 128);
+			break;
		// Extra string, first element is either 0 or end time
		case 5:
			end_time = strtol(strtok(token, ":"), NULL, 10);

			// If end is 0 this is not a hold note, just tap.
-			point->end_time = end_time ? end_time :
+			point->end_time = slider ? end_time :
				point->start_time + TAPTIME_MS;

			break;
		}

**Comment by LW2904** [comment]
Feel free to submit a PR if you'd like, I'll have a look at it tomorrow either way.
