### ISSUE TITLE
Cannot use usage commands

### ISSUE THREAD

**Issue by Zoiding** [LW2904/maniac#30]
Hello, sorry if this is quite the 'noob' issue but I can't seem to type into the executable or figure out how to actually use the options provided on the main page.  
  
I am running the "maniac-win64-static-debug.exe" version because the others return the "The code execution cannot proceed because libwinpthread-1.dl was not found. Reinstalling the program may fix this problem." error.  
  
If you could instruct me on how to use these options that would be useful for lots of testing I'm doing. 
Thank you! & Good work.

**Comment by LW2904** [comment]
The executable is designed to be run from the command line and takes arguments like any other command line program.

To run it with a humanization level of 100 and a replay humanization delta of 5 you would do `./maniac-win64-static-debug.exe -l 100 -r 5` ([screenshot](https://i.imgur.com/SAKVocQ.png))
