### ISSUE TITLE
xK maps

### ISSUE THREAD

**Issue by Hide-User** [LW2904/maniac#37]
Hi maniac support only 4K i try this and don't work on 7K maps

**Comment by LW2904** [comment]
Only 4k maps are supported at the moment. I already laid the groundwork for xk support a while ago so I'll look into getting it implemented properly in the following days.

**Comment by Hide-User** [comment]
Ok good. good luck for this :3

**Comment by LW2904** [comment]
Starting with v0.5.0 maniac now supports xk maps. I didn't test this feature exhaustively so there might still be some bugs.

**Comment by Hide-User** [comment]
Hi i test for xK and for 10K first key is same than tenth key

**Comment by LW2904** [comment]
I didn't even know 10k maps existed, I'll look into it.

**Comment by LW2904** [comment]
To me, it looks like 10k maps aren't even properly supported by the osu client, or am I missing something?

**Comment by Sensest** [comment]
That's correct I guess, there's no ranked 10k maps and only a few Loved... Thing is, I can't seem to find the config for 10k anywhere, guess they removed it?

**Comment by LW2904** [comment]
Ah, that explains why I didn't find it either, thanks! This has a low priority for now since 10k doesn't seem to be particularly popular and it'd require a lot of extra complexity to implement.

**Comment by LW2904** [comment]
>Beatmaps can only use 4 to 9 keys. Anything else is not supported for the Ranked section.

From the osu!mania [ranking criteria](https://osu.ppy.sh/help/wiki/Ranking_Criteria/osu!mania).

I'll take this as added justification that 4-9k will remain the only modes that `maniac` supports, closing now.
