### ISSUE TITLE
I want to ask

### ISSUE THREAD

**Issue by ari4431** [LW2904/maniac#42]
this program is automatically detect what beatmap we playing or we must put target dir beatmap that will be play?

**Comment by ari4431** [comment]
![image](https://user-images.githubusercontent.com/64565799/80892944-4c69c680-8cf8-11ea-85f8-174ed2cd4a82.png)
oh sorry, automatically detect beatmap is ok, but why i get error unsupported beatmap?

**Comment by LW2904** [comment]
Looks like the map finding algorithm choked, since it's trying to parse a MP3 file as a beatmap.

I'll look into it and get back to you, thanks for reporting!

**Comment by LW2904** [comment]
This issue is more or less a duplicate of #38 so I'll close this for now. I made a note of this particular issue over there, you might want to follow the other issue since I'll post there once I have a fix.
