### ISSUE TITLE
Implement game state reading from memory

### ISSUE THREAD

**Issue by LW2904** [LW2904/maniac#43]
The pattern is `A1 ? ? ? ? A3 ? ? ? ? A1 ? ? ? ? A3 ? ? ? ? 83 3D ? ? ? ? 00 0F 84 ? ? ? ? B9 ? ? ? ? E8 + 1` and leads to a 4 byte integer.

```
// 00 : Menu
// 01 : Edit
// 02 : Play
// 03 : Exit
// 04 : SelectEdit
// 05 : SelectPlay
// 06 : SelectDrawings
// 07 : Rank
// 08 : Update
// 09 : Busy
// 10 : Unknown
// 11 : Lobby
// 12 : MatchSetup
// 13 : SelectMulti
// 14 : RankingVs
// 15 : OnlineSelection
// 16 : OptionsOffsetWizard
// 17 : RankingTagCoop
// 18 : RankingTeam
// 19 : BeatmapImport
// 20 : PackageUpdater
// 21 : Benchmark
// 22 : Tourney
// 23 : Charts
```

Gotta make sure to credit [this guy](https://www.unknowncheats.me/forum/members/2498935.html).

**Comment by Hide-User** [comment]
Hi LW2904 I did not understand these latest updates. what are these updates?

**Comment by LW2904** [comment]
@Hide-User These aren't updates, they are issues -- a way to report bugs or suggest enhancements. I'm doing the latter in this case, this doesn't really concern end users.
