### ISSUE TITLE
Maniac crash without error

### ISSUE THREAD

**Issue by eryre5y** [LW2904/maniac#49]
C:\Windows\system32>"C:\Users\senpai\Desktop\maniac-v1.0.0-rc7-debug.exe"
[debug] [main] humanization: 0
[debug] [Process::get_handle] found process 'osu!.exe' with id 10552
[debug] [Process::get_handle] got handle to process 'osu!.exe' (0xb8)
[debug] [Osu::Osu] found time address: 0x2fa681c
[debug] [Osu::Osu] found player pointer: 0x4174450
[*] waiting for beatmap...
[+] found beatmap
[debug] [Osu::get_actions] got hit object manager address: 0xcccccccc
[debug] [Osu::get_actions] column count is -107374176

C:\Windows\system32>

then bot crashes

**Comment by LW2904** [comment]
Thanks for reporting this, I'm looking into it.

**Comment by LW2904** [comment]
I can reproduce this with the builds from the release section, but not if I'm building maniac locally. Strange.

**Comment by LW2904** [comment]
Just as a quick sanity check to make sure that it's not an issue with the automated build system: could you try it with the `maniac.exe` in [maniac.zip](https://github.com/LW2904/maniac/files/4727914/maniac.zip)? I build this locally and it works fine for me on both my machines.

**Comment by Sensest** [comment]
Not OP but I had the same problem and using the build you provided fixed it.

**Comment by LW2904** [comment]
@Sensest thanks for letting me know! I think I have a fix for the frequent crashes when starting a map, by the way; I'll try to figure out the build system issue before releasing that though.

**Comment by LW2904** [comment]
`v1.0.0-rc8` is out now. Code-wise it's almost the same as `v1.0.0-rc7` (except for some fixes in regards to crashing on map start) but different tooling was used to build it.

**Comment by LW2904** [comment]
I have just released `v1.0.0-rc9`. Maniac is now a 32 bit executable (again), an oversight that cost me quite a bit of time.

I can't reproduce the issue anymore, please let me know if it still happens for you.

**Comment by LW2904** [comment]
I'll assume that this is resolved, please don't hesitate to create a new issue/reopen this one if it still crashes like that for you.
