### ISSUE TITLE
Column count fetching not always reliable

### ISSUE THREAD

**Issue by LW2904** [LW2904/maniac#51]
I can't reproduce this consistently but I was made aware of the current method of fetching the column count not always being reliable.

**Comment by gonsodany** [comment]
is there a way to get this to work with 5k,6k or 7k maps? or is it just for 4k maps?

**Comment by LW2904** [comment]
It used to work for 4-9k but it looks like something broke column count reading for good on recent releases. If you really want to play on non-4k maps try `v1.0.0-rc11` (note that the interface/functionality is different -- check `maniac -h`!), it worked for me just now.

This issue has been left open for too long anyways, I'll look into it.

**Comment by gonsodany** [comment]
im using the v1.0.0-rc11debug but it only recognizes it as either 3 column or 4 column , never more than that

**Comment by LW2904** [comment]
Strangely, I can't reproduce this error with local builds -- but I can with remotely built ones, i.e. those you see in the Releases tab.

@gonsodany Could you try it with [this](https://github.com/LW2904/maniac/files/4871335/maniac.zip) build?

**Comment by LW2904** [comment]
Action parsing now takes roughly twice as much time as it used to but the column count should now always be accurate. Please note that this will break on maps that don't use the last column at all (although I doubt such maps exist).

I'd really appreciate if you could take a look at this and see if it works for you, builds with this bugfix can be downloaded [in the Actions tab](https://github.com/LW2904/maniac/actions/runs/156961074) under the 'Artifacts' header.

**Comment by LW2904** [comment]
No response yet but it still works for me and nobody is complaining yet, closing.

**Comment by gonsodany** [comment]
yes, it works with the one you send me
