### ISSUE TITLE
Release build doesn't do anything

### ISSUE THREAD

**Issue by DJKIRA** [LW2904/maniac#52]
I followed the instructions...
downloaded "maniac-v1.0.0-rc9", 
ran osu, 
played a few seconds, 
opened a cmd window (admin or regular shows no difference), 
dragged exe into it, 
pressed enter, 
cmd shows:
[*] waiting for beatmap...
[+] found beatmap
[+] parsed 2286 actions (discarded: 0)
nothing happens when... 
resuming the map, 
retrying, 
changing keys, 
changing resolution (also windowed doesn't change anything)
idk how to make this work :(

**Comment by LW2904** [comment]
Could you try the debug build and post back results? Sorry for the inconvenience and thanks for reporting the issue!

**Comment by DJKIRA** [comment]
okay, uhm, idk what happened but as soon as I did this... start maniac then start debug then resume, it worked...

**Comment by LW2904** [comment]
Well that's strange indeed. Is the release build still broken for you though?

**Comment by DJKIRA** [comment]
yes

**Comment by DJKIRA** [comment]
idk if you can implement this but it would be cool if there was an accuracy adjustment (humanizes bot by random offsets or something like that) so it seems more legit

**Comment by LW2904** [comment]
Yeah that used to be a thing pre v1.0.0 but I didn't get around to implement it yet. Should be in rc10.

**Comment by LW2904** [comment]
Hey there, does `maniac-v1.0.0-rc10.exe` work for you?

**Comment by DJKIRA** [comment]
yes, works fine...
I know it's probably hard to implement or "fix" but when setting something like "-u -4,37" the bot will FC the map without dropping a single 200 and it's kinda inhuman I guess... when setting the range even wider the bot will FC with some weird unreal ratio idk how to explain it properly but the scores just aren't looking legit at all.

**Comment by LW2904** [comment]
Yeah I know what you mean and I agree that it's hard to get humanlike scores at the moment. In any case, the current humanisation implementation is mostly a placeholder until I figure out a better way to do it; see #55 for progress notifications.

Closing this for now as it's resolved, feel free to reopen if the issue occurs again.
