### ISSUE TITLE
Maniac beatmap aspire

### ISSUE THREAD

**Issue by Hide-User** [LW2904/maniac#53]
Ahh Ahh Maniac don't really like aspire maps xD 
![Capture](https://user-images.githubusercontent.com/62671486/85125154-6705e980-b22b-11ea-99c8-133e8d6f89bb.PNG)

**Comment by LW2904** [comment]
I've been getting that error occasionally but I haven't been able to track it down. Do you get it consistently with a certain map or some other condition?

**Comment by Hide-User** [comment]
Yeah When there was discarded 0 maniac crash all the time and on the beatmap in question maniac crash often 
![Capture](https://user-images.githubusercontent.com/62671486/85126432-c2d17200-b22d-11ea-9a4b-ea7d7ff543b0.PNG)
![screenshot165](https://user-images.githubusercontent.com/62671486/85126452-c8c75300-b22d-11ea-8f4a-5b86b713ebc8.jpg)

**Comment by LW2904** [comment]
Wait so maniac crashes all the time on all beatmaps for you when there aren't any discarded actions? Are you on `v1.0.0-rc10`?

Regarding your edit: It's always 6081 actions for me on the beatmap in question, although it also always discards 3 actions right at the start.

**Comment by Hide-User** [comment]
No you do not understand it is that on this beatmap that maniac has trouble crashing once in two. and I have the latest version and for objects a hit I have 6000 another I have 4000 after 5000 it varies but only on this beatmap.
On all the others I have no problem. I think that maniac has trouble with BPM because it's a special beatmap with special paterns.

**Comment by anzenchitai** [comment]
![lol](https://user-images.githubusercontent.com/66841546/85220554-0a363a80-b3b5-11ea-9aa3-0034095bc85a.PNG)
Only happens when I try to humanize.

**Comment by LW2904** [comment]
@Hide-User did you use humanisation when you got those crashes?

**Comment by LW2904** [comment]
I'm closing this issue in favor of #54 , which collects information about the "string subscript out of range" debug assertion responsible for the crash. Feel free to follow that issue since I'll post there once I have more information.

**Comment by Hide-User** [comment]
Sorry for the delay and no i'm don't use humanization for this map
