### ISSUE TITLE
String subscript out of range

### ISSUE THREAD

**Issue by LW2904** [LW2904/maniac#54]
The MSVC Runtime occasionally reports a failed debug assertion "string subscript out of range" and aborts. I haven't been able to track this down to a specific set of beatmaps or anything like that yet, so this issue serves as a collection of information in regards to the error.

This issue supersedes #53 .

**Comment by LW2904** [comment]
I just added checks to a bunch of places where errors like this could occur. @Hide-User (sorry for tagging you again), if you'd like to try this new build out on your system you can download it by clicking [here](https://github.com/LW2904/maniac/suites/823618710/artifacts/9115524).

**Comment by Hide-User** [comment]
This time I have no more crashes and the number of objects on the betmap remains the same which means that maniac does not make miscalculations good job

**Comment by LW2904** [comment]
That's good to hear, official builds with these fixes should be up in a couple of minutes.

I'll keep this issue open in case I run across this again, doubt this is the end of it.

**Comment by LW2904** [comment]
Haven't gotten one of those in a while, closing for now.
