### ISSUE TITLE
Research and develop better humanization

### ISSUE THREAD

**Issue by LW2904** [LW2904/maniac#55]
See especially [manianalytics](https://github.com/LW2904/manianalytics) (the name is a work-in-progress, haha).

**Comment by DJKIRA** [comment]
idk I made [this](https://i.imgur.com/AaDLnXh.png) really quick in vs... maybe it helps as inspiration

**Comment by LW2904** [comment]
My current idea is more along the lines of computing a function of the density of the current map at any point in time and then just scaling that function based on the humanization level provided. The function value at a point in time could then be used as the offset for hitpoints at that time, +-0-5ms or something. I'm still not sure how viable this is, that's what the stuff in v0 is helping me find out.

In regards to your image: do you think that a flat out miss chance for every hitobject would make plays more legit? I mean I'd probably sooner suspect you of hiding something if you missed completely random notes that were really obvious/easy than if you hadn't missed those. (I also don't plan on providing a GUI in the foreseeable future, seems like too much work for too little payoff.)

**Comment by DJKIRA** [comment]
well it was just an inspirational thing but yeah it makes sense...

**Comment by DJKIRA** [comment]
I have tried a paid bot/client/hack before and it had an "unstable rate" (offsets) and "bpm streaming" slider from 150 to 300 meaning you could adjust how well the bot would hit the notes at a certain speed

**Comment by LW2904** [comment]
Stuff to think about:

Maniac without `-u`.
![](https://i.imgur.com/iPDfi6Z.png)

Maniac with `-u -10,20`.
![](https://i.imgur.com/fVl9mN4.png)

Some random replay from the global ranking
![](https://i.imgur.com/dLXIb76.png)

**Comment by LW2904** [comment]
![](https://i.imgur.com/5YhiDO3.png)

Well this looks very promising.

**Comment by DJKIRA** [comment]
damn, that's nice

**Comment by LW2904** [comment]
Global top replay of this map
![](https://i.imgur.com/a2WM2tN.png)

Maniac without `-u`
![](https://i.imgur.com/9YBNs41.png)

Two points:

- That player is insane, he's not even 100 milliseconds worse than maniac on average, what the fuck.
- Offsets produced by maniac mirror the action density the best, which is not surprising considering that maniac also takes some time to "press a key", but this time is always roughly constant. I didn't think of it/expect it though.

**Comment by DJKIRA** [comment]
I mean you could use your own replays ¯\_(ツ)_/¯

**Comment by LW2904** [comment]
I don't play osu myself, so I don't have any. If you'd like to provide some, please feel free.

**Comment by DJKIRA** [comment]
sure, do you only need the osr or the maps aswell?

**Comment by LW2904** [comment]
Yeah I need the map name as well. (At least I've not figured out a way to get the beatmap from a `.osr` file yet.)

**Comment by DJKIRA** [comment]
it will take while for me playing the maps, I'll post a google drive link or something when I'm done...
also only 4k? I can play 7k aswell but not as good as 4k...

**Comment by LW2904** [comment]
I'd prefer 4k since I've not written the analysis tool with Xk capability in mind, thanks in advance!

**Comment by DJKIRA** [comment]
okay got it.
...and do you have discord? Cuz writing here is a bit annoying...

**Comment by DJKIRA** [comment]
sharing links or whatever would be alot more comfortable

**Comment by LW2904** [comment]
Sure, fsoc#4294.

I'll delete this chain later as it doesn't really belong here.

**Comment by DJKIRA** [comment]
sent you a friend invite

**Comment by LW2904** [comment]
Cleaned up an off-topic conversation.

**Comment by LW2904** [comment]
I'm actively working on this in `humanization-refactor-1` at the moment, preview builds which may be highly unstable or not even functional can be downloaded from the [Actions tab](https://github.com/LW2904/maniac/actions?query=branch%3Ahumanization-refactor-1) (just select the most recent one and download the "builds" artifact). Run `maniac.exe -h` for information on how to control it, __the interface changed__.

I gotta say that the current implementation looks pretty decent, it drops down to 200s on dense parts but hits consistent 300s when there isn't much going on.

Parts that still need work:

- Looking at the replay in a somewhat advanced replay viewer will look really dodgy (see picture at the bottom), needs some finer randomization.
- It only _adds_ to the action times at the moment, although I guess it should mix in a couple of too-early hits as well? In any case, it should definitely increase the time spent pressing down to look more like human replays.

The same section as above but with the experimental build:

![](https://github.com/LW2904/maniac/actions?query=branch%3Ahumanization-refactor-1)

**Comment by Sensest** [comment]
I hope I'm not missing a really obvious explanation in how to use the new humanization options but I can't make it work. Is the argument supposed to be in [X] format or in a [X,Y] format?, because I tried both and none of the seems to work, it just takes the default value of 0.
Also, just wanted to ask if you're considering providing a way of donating to this project, since you're amazing and I'm sure I'm not the only one who loves your work.

**Comment by LW2904** [comment]
Ah, you're probably seeing a debug log I forgot to remove/update -- in the current build of the experimental branch the humanization is applied by default and not adjustable. For future reference, I try to keep `maniac -h` as up-to-date as possible, even on experimental branches, so it should usually serve as the source of truth.

Looks like the issue lies elsewhere though: I accidentally pushed some in-progress work in regards to allowing users to scale the offset that's actually added to the actions through a fixed modifier, this is also mentioned in `maniac -h` (which was part of the accidental push). I'll implement that real quick and post back here once I'm done.

**Comment by LW2904** [comment]
Pushed the update, `maniac -h` is now correct. I'd start with `maniac -u 100` and start experimenting from there. Please note that this is really rough around the edges right now (see the above hitpoint slider, it's really obvious) but it's a step in the right direction.

**Comment by LW2904** [comment]
@Sensest After thinking about this for a bit, I'm not so sure about donations. Maybe I'll reconsider once the project has matured a bit and set up a Patreon or something. Or maybe I'll offer a version with some QOL improvements (a GUI, for example) that'll be something like 5$/month, at some point. Not sure yet, definitely going to work on a solid base of features before I consider anything like that though.

In other news, I played around with the dataset some more and separated the absolute error in a timeframe into a positive (i.e. too early) and a negative (i.e. too late) part:

![](https://i.imgur.com/qdhp6NE.png)

What's interesting about this is that it shows that early keypresses are (a) significantly more rare than late ones and (b) almost completely independent of the beatmap density. This probably won't factor into the humanization algorithm immediately since it's more of a post release polish but interesting to know nevertheless.

**Comment by LW2904** [comment]
I recently pushed some changes that would add a random offset between -5 and 5ms to every humanized action when using the new experimental humanization. I feel like this should be customizable. Perhaps with `--humanization` for the offset that scales with density and `--randomization` (or maybe `--static-humanization...`?) for random offsets in a static range.

**Comment by LW2904** [comment]
I have to refactor the config parsing because it turns out that the library I was using previously incorrectly handles some cases that I really want to have(default and implicit arguments, most notably). I consider the experimental humanization mostly stable at this point in time so this is essentially the only thing that's holding back a merge into master at this point. Soon.

**Comment by LW2904** [comment]
Config refactor is done. I'll wait a couple of days and if nobody starts screaming by then I'll merge the humanization refactor (+ config refactor I guess) into master. At which point I will probably take a break from this project for a little while.

**Comment by LW2904** [comment]
Merged, I'll close this now since the original goal of this issue (to develop better humanization) has been met. Once I can think of more improvements I'll open an issue, I'll of course also be happy to review suggestions in regards to this.

New release should be up in a bit.
